site_name: Buildy
site_url: https://kello54.github.io/Buildy/
site_description: Buildy.ie – building material price comparison website

theme:
  name: material
  palette:
    - scheme: default
      primary: purple
      accent: amber
  logo: images/logo.png   # shows in header

nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
