site_name: Buildy
site_url: https://kello54.github.io/Buildy/
site_description: Building Material Price Comparison

theme:
  name: material
  language: en
  logo: images/logo.png
  favicon: images/favicon.png
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - toc.integrate
    - search.suggest
    - search.highlight
    - header.autohide
    - content.action.edit

extra_css:
  - stylesheets/custom.css

nav:
  - Home: index.md
  - About: about.md
  - Features: features.md
  - Pricing: pricing.md
  - FAQ: faq.md
  - Roadmap: roadmap.md
  - Contact: contact.md 
