site_name: V18 Platform Docs
theme: material
plugins:
  - search
  - swagger-ui:
      swagger_path: platform.json

nav:
  - Home: docs/index.md
  - Runbooks: docs/runbooks.md
  - Dashboards: docs/dashboards.md
  - API:
      - Quotasvc: quotasvc.json
      - Workers: workers.json
      - Full Platform: platform.json
