site_name: V18 Platform Docs
theme:
  name: material

plugins:
  - search
  - swagger-ui:
      spec_file: docs/platform.json
      path: api   # this will serve your API docs at /api/

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API: api/index.html
