site_name: V18 Platform Docs
site_url: https://kello54.github.io/Buildy/
site_description: Documentation for the V18 Platform

theme:
  name: material

plugins:
  - search
  - swagger-ui:
      spec_file: docs/platform.json

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Runbooks:
      - Overview: runbooks/index.md
      - Runbook 1: runbooks/runbook1.md
      - Runbook 2: runbooks/runbook2.md
  - Dashboards:
      - Dashboard 1: dashboards/dashboard1.md
      - Dashboard 2: dashboards/dashboard2.md
  - API Reference: api.md
  - Platform: platform.md
