site_name: V18 Platform Docs
site_description: Documentation for the V18 Platform
site_author: V18 Team

theme:
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight

plugins:
  - search
  - swagger-ui:
      swagger_path: docs/platform.json

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API: swagger-ui
