site_name: V18 Platform Docs
site_url: https://kello54.github.io/Buildy/
site_description: Documentation for the V18 Platform

theme:
  name: material

plugins:
  - search
  - swagger-ui:
      spec_file: docs/platform.json

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Runbooks: runbooks/index.md
  - API: api.md
  - Platform: platform.md
