site_name: V18 Platform Docs
theme: material
plugins:
  - search
  - swagger-ui:
      swagger_path: openapi/platform.json

nav:
  - Home: docs/index.md
  - Runbooks: docs/runbooks.md
  - Dashboards: docs/dashboards.md
  - API:
      - Quotasvc: openapi/generated/quotasvc.json
      - Workers: openapi/generated/workers.json
      - Full Platform: openapi/platform.json
