site_name: V18 Platform Docs
theme: material

plugins:
  - search
  - swagger-ui:
      specs:
        - name: Full Platform
          path: docs/platform.json
        - name: Quotasvc
          path: docs/quotasvc.json
        - name: Workers
          path: docs/workers.json

nav:
  - Home: index.md
  - Runbooks: docsrunbooks.md
  - Dashboards: dashboards.md
  - API:
      - Quotasvc: quotasvc.json
      - Workers: workers.json
      - Full Platform: platform.json
