site_name: V18 Platform Docs

theme:
  name: material

plugins:
  - search
  - swagger-ui:
      url: docs/platform.json   # fixed

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API:
      - Platform API: platform.json
