site_name: Buildy Docs

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png

plugins:
  - search

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboard: dashboard.md
