site_name: Buildy
site_url: https://kello54.github.io/Buildy/
site_description: Documentation for the Buildy platform

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple   # purple theme
      accent: amber          # gold accents
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/logo.png        # logo you uploaded
  favicon: images/favicon.png  # favicon you uploaded

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - About: about.md
  - Features: features.md
  - Pricing: pricing.md
  - FAQ: faq.md
  - Roadmap: roadmap.md
  - Changelog: changelog.md
  - Contact: contact.md
