site_name: Buildy Docs
site_description: Documentation for the Buildy platform
site_author: Buildy Team
repo_url: https://github.com/Kello54/Buildy
repo_name: Kello54/Buildy

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
  font:
    text: "Inter"
    code: "Fira Code"

extra_css:
  - stylesheets/custom.css

plugins:
  - search
  - swagger-ui:
      spec_file: docs/platform.json

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API Reference:
      - API Spec: swagger.json
      - API Docs: api.md
  - Quotas: quotasvc.json


