site_name: V18 Platform Docs

theme:
  name: material

plugins:
  - search
  - swagger-ui:
      spec: docs/platform.json   # ✅ fixed from spec_file to spec

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API:
      - Platform API: platform.json
