site_name: V18 Platform Docs
strict: true

theme:
  name: material
  palette:
    primary: deep purple
    accent: amber

plugins:
  - search
  - swagger-ui-tag
  - link-checker

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API: api.md
  - Troubleshooting: troubleshooting.md
  - Changelog: changelog.md
  - Contributing: contributing.md
