site_name: V18 Platform Docs
site_url: https://kello54.github.io/buildy/
site_description: "Documentation for the V18 Platform"

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search
  - swagger-ui:
      spec_file: docs/platform.json

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md