site_name: V18 Platform Docs
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png

plugins:
  - search
  - swagger-ui:
      spec_file: docs/platform.json

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API: api.md
  - Architecture: architecture.md
  - Changelog: changelog.md
  - Contributing: contributing.md
  - Branding:
      - Overview: branding/index.md
      - Logo: branding/logo.md
      - Colors: branding/colors.md
      - Typography: branding/typography.md
