site_name: Buildy
site_url: https://kello54.github.io/Buildy/
site_description: Building material price comparison app

theme:
  name: material
  logo: images/logo.png       # your logo
  favicon: images/favicon.png # your favicon
  palette:
    primary: purple
    accent: amber
  features:
    - navigation.top
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Kello54/Buildy
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourprofile

plugins:
  - search

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true

# Load your overrides for custom footer
theme:
  name: material
  custom_dir: overrides

nav:
  - Home: index.md
  - About: about.md
  - Docs:
      - Getting Started: docs/getting-started.md
      - FAQ: docs/faq.md
