site_name: V18 Platform Docs
theme:
  name: material

plugins:
  - search
  - swagger-ui:
      spec_file: docs/platform.json

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API: api.md
  - Branding:
      - Overview: branding/index.md
      - Logo: branding/logo.md
      - Colors: branding/colors.md
      - Typography: branding/typography.md


