site_name: V18 Platform Docs
theme:
  name: material

plugins:
  - search
  - swagger-ui-tag:
      spec: docs/platform.json
  - git-revision-date-localized:
      fallback_to_build_date: true
  - minify:
      minify_html: true
  - redirects

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API: api.md
