site_name: V18 Platform Docs
theme:
  name: material

plugins:
  - search
  - swagger-ui:
      specs:
        - file: docs/platform.json
  - mike

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API: platform.json
