site_name: V18 Platform Docs
theme:
  name: material

plugins:
  - search
  - swagger-ui
  - mike

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API:
      - Platform Spec: platform.json
