site_name: V18 Platform Docs

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png

plugins:
  - search
  - swagger-ui:
      spec_file: docs/platform.json

nav:
  - Home: index.md
  - Runbooks:
      - Overview: runbooks/index.md
      - Dashboards: runbooks/dashboards.md
  - API: api.md
  - Platform: platform.md
