site_name: V18 Platform Docs
site_description: Documentation for the V18 Platform
site_author: V18 Team
repo_url: https://github.com/YOUR-USERNAME/YOUR-REPO

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - search.suggest
    - search.highlight
    - content.code.copy
  palette:
    - scheme: default
      primary: blue
      accent: indigo

plugins:
  - search
  - swagger-ui:
      spec_file: docs/platform.json

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API:
      - Reference: platform.json
