site_name: V18 Platform Docs

theme:
  name: material

plugins:
  - search
  - swagger-ui:
      specs:
        - file: docs/platform.json   # ✅ fixed
          name: Platform API

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API:
      - Platform API: platform.json
