site_name: V18 Platform Docs

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search
  - swagger-ui:
      spec_file: docs/platform.json
  - swagger-ui:
      spec_file: docs/swagger.json
  - swagger-ui:
      spec_file: docs/workers.json
  - swagger-ui:
      spec_file: docs/quotasvc.json

nav:
  - Home: index.md
  - Runbooks:
      - Overview: runbooks/index.md
  - Dashboards:
      - Overview: dashboards/index.md
  - API:
      - Platform: api/platform.md
      - Swagger: api/swagger.md
      - Workers: api/workers.md
      - Quotas: api/quotasvc.md
