site_name: Buildy Platform Docs
site_url: https://kello54.github.io/Buildy/
site_description: Documentation for the Buildy platform

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API: api.md
  - Platform: platform.md

plugins:
  - search
  - swagger-ui:
      spec_file: docs/platform.json

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
