site_name: V18 Platform Docs
theme:
  name: material

plugins:
  - search
  - swagger-ui:
      specs:
        - name: Platform API
          path: docs/platform.json

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API:
      - Platform: platform.json
