site_name: Buildy Docs
site_description: Documentation for the Buildy platform
site_url: https://kello54.github.io/Buildy/

theme:
  name: material
  palette:
    - scheme: default
      primary: deep_purple
      accent: amber
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - API Reference: api.md
  - Architecture: architecture.md
  - Dashboards: dashboards.md
  - Runbooks: runbooks.md
  - Changelog: changelog.md
  - Contributing: contributing.md
  - JSON Specs:
      - Platform: platform.json
      - Quota Service: quotasvc.json
      - Swagger: swagger.json
      - Workers: workers.json
