site_name: V18 Platform Docs

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search
  - swagger-ui:
      spec_file: docs/platform.json

nav:
  - Home: index.md
  - Runbooks: runbooks/index.md
  - Dashboards: dashboards/index.md
  - API: api/index.md
