site_name: V18 Platform Docs

theme:
  name: material

plugins:
  - search
  - swagger-ui:
      swagger_ui: docs/platform.json

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API: swagger-ui
