site_name: V18 Platform Docs
site_url: https://kello54.github.io/Buildy/
repo_url: https://github.com/kello54/Buildy

theme:
  name: material
  logo: images/logo.png         # ✅ docs/images/logo.png
  favicon: images/favicon.png   # ✅ docs/images/favicon.png
  palette:
    - scheme: default
      primary: deep purple      # main header color
      accent: amber             # gold highlight
    - scheme: slate
      primary: deep purple
      accent: amber
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search
  - swagger-ui:
      spec_file: docs/platform.json   # ✅ your actual file

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API: platform.json
