site_name: Buildy Docs
site_description: Documentation for Buildy
site_author: Buildy Team

theme:
  name: material
  logo: images/logo.PNG
  favicon: images/favicon.png
  palette:
    - scheme: default
      primary: deep purple    # Main purple tone
      accent: amber           # Golden accent
    - scheme: slate           # Optional dark mode
      primary: deep purple
      accent: amber
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-org/your-repo
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/your-handle

