site_name: V18 Platform Docs
theme:
  name: material

plugins:
  - search
  - swagger-ui:
      - file: docs/platform.json   # Path to your API spec

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API:
      - Platform API: platform.json
