site_name: Buildy
site_url: https://kello54.github.io/
site_description: Buildy - Building material price comparison platform

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: purple
      accent: amber
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight

nav:
  - Home: index.md
  - About: about.md
  - Features: features.md
  - Pricing: pricing.md
  - FAQ: faq.md
  - Getting Started: getting-started.md
  - Roadmap: roadmap.md
  - Changelog: changelog.md
  - Contact: contact.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - def_list
  - attr_list
  - md_in_html
  - tables
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.emoji
