site_name: V18 Platform Docs
site_description: Documentation for the V18 platform
site_url: https://Kello54.github.io/Buildy/

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest

nav:
  - Home: index.md
  - Guides:
      - API: api.md
      - Architecture: architecture.md
      - Dashboards: dashboards.md
      - Runbooks: runbooks.md
  - Project:
      - Changelog: changelog.md
      - Contributing: contributing.md
  - Branding:
      - Overview: branding/index.md
      - Colours: branding/colours.md
      - Logo: branding/logo.md
      - Typography: branding/typography.md

plugins:
  - search


