site_name: V18 Platform Docs
theme: material

plugins:
  - search
  - swagger-ui:
      specs:
        - file: platform.json
        - file: quotasvc.json
        - file: workers.json

nav:
  - Home: index.md
  - Runbooks: docsrunbooks.md
  - Dashboards: dashboards.md
  - API:
      - Quotasvc: quotasvc.json
      - Workers: workers.json
      - Full Platform: platform.json
