site_name: Buildy Platform Docs
site_description: Documentation for the Buildy platform
site_author: Buildy Team

theme:
  name: material
  logo: images/logo.png
  favicon: images/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search
  - swagger-ui:
      spec_file: docs/platform.json
  - swagger-ui:
      spec_file: docs/swagger.json
  - swagger-ui:
      spec_file: docs/workers.json
  - swagger-ui:
      spec_file: docs/quotasvc.json

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API:
      - API Overview: api.md
      - Platform: platform.json
      - Quota Service: quotasvc.json
      - Workers: workers.json
      - Swagger: swagger.json
  - Architecture: architecture.md
  - Contributing: contributing.md
  - Changelog: changelog.md
