site_name: Buildy - TEST CHANGE
site_url: https://kello54.github.io/
site_description: Compare building material prices

theme:
  name: material
  palette:
    primary: red
    accent: lime
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/logo.jpeg   # or .jpg / .png depending on your actual file

nav:
  - Home: index.md
  - Features: features.md
  - Pricing: pricing.md
  - About: about.md
  - Contact: contact.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
