site_name: Buildy
site_url: https://kello54.github.io/Buildy/
site_description: Documentation for the Buildy platform

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple   # purple theme
      accent: amber          # gold accent
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/logo.png      # change to logo.jpeg if needed
  # favicon removed until you have one

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
