site_name: Buildy
site_url: https://kello54.github.io/buildy/
site_description: Construction Price Comparison Platform

theme:
  name: material
  palette:
    primary: purple
    accent: yellow
  font:
    text: Inter
    code: Roboto Mono
  favicon: images/favicon.ico    # optional
  logo: images/logo.png          # optional
  features:
    - navigation.expand
    - navigation.sections
    - toc.integrate
    - search.highlight
    - search.suggest

# Custom CSS
extra_css:
  - css/custom.css

# Extra JS (optional)
extra_javascript:
  - js/back-to-top.js

# Site navigation
nav:
  - Home: index.md
  - About: about.md
  - Comparison: comparison.md
  - Contact: contact.md

# Repository info (for GitHub integration/edit buttons)
repo_name: Kello54/buildy
repo_url: https://github.com/Kello54/buildy
edit_uri: edit/main/docs/
