site_name: V18 Platform Docs
site_description: Documentation for the V18 platform
site_url: https://Kello54.github.io/Buildy/

theme:
  name: material

nav:
  - Home: index.md
  - Guides:
      - API: api.md
      - Architecture: architecture.md
      - Dashboards: dashboards.md
      - Runbooks: runbooks.md
  - Project:
      - Changelog: changelog.md
      - Contributing: contributing.md
  - Branding:
      - Overview: branding/index.md
      - Colours: branding/colours.md
      - Logo: branding/logo.md
      - Typography: branding/typography.md

plugins:
  - search

