site_name: V18 Platform Docs

theme:
  name: material

plugins:
  - search
  - swagger-ui-tag:
      swagger_ui: 
        urls:
          - name: Platform API
            url: docs/platform.json

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API: api.md
