site_name: V18 Platform Docs
site_url: https://kello54.github.io/Buildy/   # replace with your repo Pages URL
theme:
  name: material
  logo: images/logo.png      # path inside docs/
  favicon: images/favicon.png
  palette:
    scheme: default
    primary: blue
    accent: deep purple

plugins:
  - search
  - swagger-ui:
      spec_file: docs/platform.json

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API:
      - Quotasvc: quotasvc.json
      - Workers: workers.json
      - Full Platform: platform.json
