site_name: Buildy
site_url: https://yourusername.github.io/buildy/
site_description: Construction Price Comparison Platform

theme:
  name: material
  palette:
    primary: purple
    accent: yellow
  font:
    text: Inter
    code: Roboto Mono
  favicon: images/favicon.ico  # optional
  logo: images/logo.png        # optional
  features:
    - navigation.expand
    - navigation.sections
    - toc.integrate
    - search.highlight
    - search.suggest

# Include your custom CSS
extra_css:
  - css/custom.css

# Enable extra JS if needed (optional)
extra_javascript:
  - js/back-to-top.js   # optional for back-to-top functionality

# Site navigation
nav:
  - Home: index.md
  - About: about.md
  - Comparison: comparison.md
  - Contact: contact.md

# Repository info (for GitHub edit links)
repo_name: yourusername/buildy
repo_url: https://github.com/yourusername/buildy
edit_uri: edit/main/docs/
