site_name: Buildy Docs
site_description: Buildy Documentation Platform
site_author: Buildy Team
site_url: https://kello54.github.io/Buildy/

# Theme
theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png
  palette:
    - scheme: default
      primary: deep purple
      accent: amber
    - scheme: slate
      primary: deep purple
      accent: amber
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.highlight
    - search.share
    - content.code.copy

# Extra CSS (custom branding)
extra_css:
  - stylesheets/custom.css

# Plugins
plugins:
  - search
  - swagger-ui:
      spec_file: docs/platform.json

# Navigation
nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API:
      - API Reference: api.md
      - Swagger Spec: swagger.json
  - Platform: platform.json
  - Quotas: quotasvc.json

