site_name: V18 Platform Docs
theme:
  name: material

plugins:
  - search
  - swagger-ui:
      swagger_path: docs/platform.json
  - swagger-ui:
      swagger_path: docs/quotasvc.json
  - swagger-ui:
      swagger_path: docs/workers.json

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API:
      - Platform: platform.json
      - Quota Service: quotasvc.json
      - Workers: workers.json
