site_name: V18 Platform Docs

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png

plugins:
  - search

nav:
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API: api.md
  - Architecture: architecture.md
  - Changelog: changelog.md
  - Contributing: contributing.md
  - Branding: branding/index.md
