site_name: V18 Platform Docs
site_description: Documentation for the V18 platform
site_url: https://YOUR_USERNAME.github.io/YOUR_REPO/

theme:
  name: material

nav:
  - Home: index.md
  - API: api.md
  - Platform: platform.md

plugins:
  - search

