site_name: V18 Platform Docs

theme:
  name: material

plugins:
  - search
  - swagger-ui:
      spec_file: platform.json   # docs/ prefix removed
  - minify:
      minify_html: true

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API:
      - Platform API: platform.json
