site_name: Buildy
site_url: https://kello54.github.io/Buildy/
site_description: Documentation for the Buildy platform

theme:
  name: material
  palette:
    primary: deep purple   # main purple colour
    accent: amber          # gold accent colour
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/logo.jpeg      # adjust if your file is jpeg
  favicon: images/logo.jpeg   # temporary favicon

nav:
  - Home: index.md
  - About: about.md
  - Docs:
      - Getting Started: getting-started.md
      - Features: features.md
      - Pricing: pricing.md
  - Contact: contact.md
