site_name: V18 Platform Docs
theme:
  name: material

plugins:
  - search
  - swagger-ui:
      spec_file: docs/platform.json
  - link-checker   # checks for broken links

strict: true

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API: api.md
