site_name: Buildy
site_url: https://kello54.github.io/Buildy/
site_description: Documentation for the Buildy platform

theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: deep purple
      accent: amber

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Usage: usage.md
  - API Reference: api-reference.md

plugins:
  - search

