site_name: Buildy Docs
site_description: Documentation for the Buildy Platform
site_url: https://kello54.github.io/Buildy/

theme:
  name: material
  palette:
    - scheme: default
      primary: deep_purple
      accent: amber
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Usage: usage.md
  - API Reference: api.md
