site_name: V18 Platform Docs
theme:
  name: material

plugins:
  - search
  - swagger-ui:
      spec_file: docs/platform.json   # <— fixed option name

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API: platform.json
