site_name: V18 Platform Docs
site_url: https://<your-username>.github.io/<your-repo>/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search
  - swagger-ui:
      swagger: docs/platform.json

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API Reference: platform.json
