site_name: Buildy
site_url: https://kello54.github.io/Buildy/
site_description: Building material price comparison platform

theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple   # purple theme
      accent: amber          # gold accent
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/logo.png
  features:
    - navigation.footer      # footer prev/next links
    - navigation.top         # sticky top nav bar
    - navigation.expand      # expanded sidebar
    - toc.integrate          # integrate page TOC into sidebar
    - content.code.copy      # "copy" button on code blocks

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - About: about.md
  - Features: features.md
  - Pricing: pricing.md
  - FAQ: faq.md
  - Roadmap: roadmap.md
  - Changelog: changelog.md
  - Contact: contact.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Kello54
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/solid/envelope
      link: mailto:support@buildy.example

extra_footer: |
  <p style="text-align: center;">
    © 2025 Buildy — All rights reserved.<br>
    Made with ❤️ using <a href="https://www.mkdocs.org/">MkDocs</a> and 
    <a href="https://squidfunk.github.io/mkdocs-material/">Material for MkDocs</a>.
  </p>
