site_name: Buildy
site_url: https://kello54.github.io/Buildy/
site_description: Documentation for the Buildy platform

theme:
  name: material
  palette:
    primary: deep purple   # purple theme
    accent: amber          # gold accent
  font:
    text: Roboto
    code: Roboto Mono
        
  # favicon removed until you have one

plugins:
  - search
  - cachebuster   # stops Safari/Chrome from loading old cached site

nav:
  - Home: index.md
  - About: about.md
  - Docs:
      - Getting Started: getting-started.md
      - Features: features.md
      - Pricing: pricing.md
  - Contact: contact.md
