site_name: V18 Platform Docs
site_url: https://kello54.github.io/V18/
site_description: Documentation for the V18 platform

theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - content.code.copy
    - content.action.edit

plugins:
  - search
  - swagger-ui-tag:
      spec: docs/swagger.json
  - swagger-ui-tag:
      spec: docs/platform.json
  - swagger-ui-tag:
      spec: docs/workers.json
  - swagger-ui-tag:
      spec: docs/quotasvc.json

nav:
  - Home: index.md
  - API Docs:
      - Overview: swagger.md
      - Main API: swagger.json
      - Platform API: platform.json
      - Workers API: workers.json
      - Quota Service API: quotasvc.json
