site_name: V18 Platform Docs
theme:
  name: material

plugins:
  - search
  - swagger-ui-tag:
      urls:
        - name: Platform
          url: docs/platform.json
        - name: Quota Service
          url: docs/quotasvc.json
        - name: Workers
          url: docs/workers.json

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API:
      - Platform: platform.json
      - Quota Service: quotasvc.json
      - Workers: workers.json
