site_name: V18 Platform Docs
theme:
  name: material

plugins:
  - search
  - swagger-ui:
      spec_file:
        - docs/swagger.json
        - docs/quotasvc.json
        - docs/workers.json
        - docs/platform.json

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API:
      - API Guide: api.md
      - Main API: swagger.json
      - Quota Service: quotasvc.json
      - Workers: workers.json
      - Platform: platform.json
