site_name: V18 Platform Docs
site_url: https://kello54.github.io/V18/
site_description: Documentation for the V18 platform

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.png

plugins:
  - search
  - swagger-ui:
      spec_file: docs/platform.json

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Runbooks:
