site_name: V18 Platform Docs
theme: material

plugins:
  - search
  - swagger-ui

nav:
  - Home: index.md
  - Runbooks: runbooks.md
  - Dashboards: dashboards.md
  - API:
      - Quotasvc: quotasvc.json
      - Workers: workers.json
      - Full Platform: platform.json
