site_name: V18 Platform Docs
site_description: Documentation for the V18 platform
site_url: https://Kello54.github.io/Buildy/

theme:
  name: material

nav:
  - Home: index.md
  - API: api.md
  - Architecture: architecture.md
  - Changelog: changelog.md
  - Contributing: contributing.md
  - Dashboards: dashboards.md
  - Runbooks: runbooks.md
  - Branding:
      - Overview: branding/index.md
      - Colours: branding/colours.md
      - Logo: branding/logo.md
      - Typography: branding/typography.md

plugins:
  - search
