name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
  run: |
    pip install mkdocs-material
    pip install mkdocs-swagger-ui-tag

      - name: Validate OpenAPI spec
        run: |
          python -m openapi_spec_validator docs/swagger.json

      - name: Build site
        run: |
          mkdocs build --strict --clean

      - name: Generate Swagger Preview
        run: echo "Swagger preview generated"

      - name: Upload site artifact
        uses: actions/upload-artifact@v3
        with:
          name: site
          path: site
