name: Deploy MkDocs

on:
  push:
    branches:
      - main   # or 'master' depending on your repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install MkDocs and plugins
        run: |
          pip install mkdocs-material
          pip install mkdocs-swagger-ui

      - name: Build and deploy
        run: mkdocs gh-deploy --force
